apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-calc
  labels:
    app: python-calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-calc
  template:
    metadata:
      labels:
        app: python-calc
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: python-calc
          image: __IMAGE__
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 20
