apiVersion: v1
kind: Service
metadata:
  name: python-calc
  labels:
    app: python-calc
spec:
  type: ClusterIP
  selector:
    app: python-calc
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
